# Generated by Django 2.2.1 on 2019-05-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190506_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aboutme',
            field=models.TextField(blank=True, default='这个人很懒，什么都没有留下'),
        ),
    ]
