# Generated by Django 2.2.1 on 2019-05-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190507_1542'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='article',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
